In [1]:
import pandas as pd
import numpy as np

In [2]:
con_1 = pd.read_csv('강서구 편의점.csv')
con_1.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,20698098,CU,강서태양점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150000e+24,베스트힐타운,서울특별시 강서구 강서로18길 146,157010,7745,NaN,1,NaN,126.853607,37.535125
1,24269630,세븐일레븐,화곡수명점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150000e+24,NaN,서울특별시 강서구 강서로33길 103,157924,7711,NaN,1,NaN,126.834220,37.540522
2,24218680,세븐일레븐,강서내발산길점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150000e+24,신약국,서울특별시 강서구 강서로45라길 35,157835,7638,NaN,1,NaN,126.834082,37.549387
3,28524181,CU,수명파크점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150000e+24,마곡수명산파크3단지아파트,서울특별시 강서구 수명로1길 110,157933,7643,NaN,1,NaN,126.824639,37.551852
4,11719625,CU,마곡아르디에점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1.150000e+24,아르디에,서울특별시 강서구 강서로 423,157210,7792,NaN,1,NaN,126.839341,37.563495

###  필요한 컬럼만 추출

In [3]:
con_1.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [4]:
con_1.columns # 상호명, 지점명, 도로명주소, 경도, 위도
con_1 = con_1[['상호명','지점명','지번주소','도로명주소','경도','위도']]

con_1.head(1)

  상호명    지점명                 지번주소                 도로명주소          경도         위도
0  CU  강서태양점  서울특별시 강서구 화곡동 161-2  서울특별시 강서구 강서로18길 146  126.853607  37.535125

### 데이터 전처리

In [5]:
con_1.상호명.unique() # CU, 세븐일레븐, GS25, 미니스톱, 이마트24을 대상으로 추출

array(['CU', '세븐일레븐', '이마트', 'GS25등촌스타점', '썬플러스', 'CU방화진흥점', '예스플러스강서화곡점',
       '365플러스편의점화곡우리점', 'GS25', 'SK네트웍스해바라기', '세븐일레븐화곡곰달래지점', '미니스톱',
       '세븐일레븐강서등촌점', '세븐일레븐등촌역점', 'C,U정원점', 'GS25화곡대원점', '세븐일레븐마곡럭스점',
       '인더라인25', '위드미마곡에코점', '위드미강서화곡점', '헬로앨리스마켓24', '지에스더프레쉬', '올리브영',
       'GS25강서IT밸리점', '세븐일레븐공항시장점', 'GS25화곡풀향기', 'GS25방화대림점', 'CU화곡에스점',
       '세븐일레븐강서등촌로점', '이마트24', '세븐일레븐화곡중앙점', '24시편의점', 'CUSK가양주유소점',
       'GS25화곡행복점', '세븐일레븐가양프라자점B', 'CU방화오피스2호점', '세븐일레븐등촌현대점', 'CU발산수명점',
       '지에스25화곡달빛', '씨유화곡소비자', '위드미', '지에스25발산1단지', 'GS25마곡라마다점',
       'CU송정공항점', '위드미강서등촌점', '지에스25마곡14단지', '위드미가양역점', '365PLUS우장산현대점',
       '세븐일레븐강서화곡진주점', 'CU방화해피점', '위드미마곡미르웰점', 'CU화곡와이즈점', '비지에프휴먼넷904',
       '샐러디', '코리아세븐강서', '미니스톱강서우장산점', 'GS25곰달래로', '에스아이씨유', '미니스톱가양점',
       '위드미강서등마루점', '제이케이블라썸편의점', 'GS25화곡본', '인더라인25시편의점', 'CU방화행운점',
       '미니스톱화곡사거리점', '비지에프휴먼넷910', 'GS25화곡한빛', '지에스25방화대림', 'CU뉴화곡우리마을',
       '지에스25등촌캐빈', 'GEESSI신발편의점', '비지에프휴먼넷항공지원센터점',
       '세븐일레븐롯데스카이파크점롯데스카이파크점', 'GS25화곡비젼점', '데이앤나이트', '편의점사랑',
       '비지에프리테일화곡보리점', '서울식물원푸드이마트24편의점', '휴게음식점', 'GS25마곡8단지',
       '씨유한솔할인마트', '보광훼미리마트화곡수명', '편의점&카페24', '코리아세븐등촌샤르망', 'CU가양휴먼빌점',
       '위드미마곡일성점', 'GS25강서메르디앙점', 'GS25염창빌리지점', '내발산GS', 'CU강서다온점',
       '인더라인24시편의점가양점', 'CU방화오피스점', 'GS25마곡힐스테이트점', 'GS25강서타운점',
       '세븐일레븐가양한림점', 'GS25김포공항역점', 'GS25편의점', 'CU강서붐호텔점', '미니스톱비즈메트로점',
       '세븐일레븐마곡마커스점', '코리아세븐강서공항대로점', '지에스25방화샤르망', '훼미리마트화곡PMK',
       '코레일유통김포공항편의점', '지에스25화곡역매점', '백컵스', '비지에프휴먼넷901', '비지에프휴먼넷907',
       '비지에프휴먼넷906향천향교역점', 'CU발산열린점', '비지에프휴먼넷909', 'GS25강서센트레점',
       '세븐일레븐S방화역점', '씨제이올리브네트웍스송정', 'GS25화곡가로공원점', '우장산점', 'GS25발산1단지점',
       '티엠씨에이치', '지에스화곡들판점', '비지에프리테일화곡1동점', '미니스톱등촌청림점', 'GS25화곡대원',
       '편의점GS25', 'CU가양모터리움점', '세븐일레븐2872S개화산역점', '씨유티', '응응스크르',
       '지에스화곡나누리점', '착한가게24', '지에스', '헬시박스', '패밀리샵', '웨더', '코리아세븐마곡1',
       '코리아세븐화곡우장산숲점', '신구멍가게24', '코리아세븐방화방', '코리아세븐염창래미안점',
       '코리아세븐화곡자하클래식점', '온기', '코리아세븐항공지원센터점', '비지에프리테일공항',
       '코리아세븐김포공항버스정류장점', '코리아세븐가양9단지점', '코리아세븐마곡', '코리아세븐마곡이너매스점'],
      dtype=object)

In [6]:
#상호명에 CU,세븐일레븐,GS25,이마트24,지에스25,미니스톱 가 포함되는 데이터만 추출
gs_con = con_1[con_1.상호명.str.contains('CU|세븐일레븐|GS25|지에스25|이마트24|미니스톱')]
gs_con.head()

,상호명,지점명,지번주소,도로명주소,경도,위도
0,CU,강서태양점,서울특별시 강서구 화곡동 161-2,서울특별시 강서구 강서로18길 146,126.853607,37.535125
1,세븐일레븐,화곡수명점,서울특별시 강서구 화곡동 1068,서울특별시 강서구 강서로33길 103,126.834220,37.540522
2,세븐일레븐,강서내발산길점,서울특별시 강서구 내발산동 716-24,서울특별시 강서구 강서로45라길 35,126.834082,37.549387
3,CU,수명파크점,서울특별시 강서구 내발산동 751,서울특별시 강서구 수명로1길 110,126.824639,37.551852
4,CU,마곡아르디에점,서울특별시 강서구 마곡동 784-13,서울특별시 강서구 강서로 423,126.839341,37.563495

In [7]:
gs_con.상호명.unique()

array(['CU', '세븐일레븐', 'GS25등촌스타점', 'CU방화진흥점', 'GS25', '세븐일레븐화곡곰달래지점',
       '미니스톱', '세븐일레븐강서등촌점', '세븐일레븐등촌역점', 'GS25화곡대원점', '세븐일레븐마곡럭스점',
       'GS25강서IT밸리점', '세븐일레븐공항시장점', 'GS25화곡풀향기', 'GS25방화대림점', 'CU화곡에스점',
       '세븐일레븐강서등촌로점', '이마트24', '세븐일레븐화곡중앙점', 'CUSK가양주유소점', 'GS25화곡행복점',
       '세븐일레븐가양프라자점B', 'CU방화오피스2호점', '세븐일레븐등촌현대점', 'CU발산수명점', '지에스25화곡달빛',
       '지에스25발산1단지', 'GS25마곡라마다점', 'CU송정공항점', '지에스25마곡14단지',
       '세븐일레븐강서화곡진주점', 'CU방화해피점', 'CU화곡와이즈점', '미니스톱강서우장산점', 'GS25곰달래로',
       '미니스톱가양점', 'GS25화곡본', 'CU방화행운점', '미니스톱화곡사거리점', 'GS25화곡한빛',
       '지에스25방화대림', 'CU뉴화곡우리마을', '지에스25등촌캐빈', '세븐일레븐롯데스카이파크점롯데스카이파크점',
       'GS25화곡비젼점', '서울식물원푸드이마트24편의점', 'GS25마곡8단지', 'CU가양휴먼빌점',
       'GS25강서메르디앙점', 'GS25염창빌리지점', 'CU강서다온점', 'CU방화오피스점', 'GS25마곡힐스테이트점',
       'GS25강서타운점', '세븐일레븐가양한림점', 'GS25김포공항역점', 'GS25편의점', 'CU강서붐호텔점',
       '미니스톱비즈메트로점', '세븐일레븐마곡마커스점', '지에스25방화샤르망', '지에스25화곡역매점', 'CU발산열린점',
       'GS25강서센트레점', '세븐일레븐S방화역점', 'GS25화곡가로공원점', 'GS25발산1단지점',
       '미니스톱등촌청림점', 'GS25화곡대원', '편의점GS25', 'CU가양모터리움점', '세븐일레븐2872S개화산역점'],
      dtype=object)

In [8]:
# 상호명 잘못 저장된 데이터 list에 저장
con_name = gs_con.상호명.unique().tolist()
con_name = [name for name in con_name if name not in ['GS25','CU','이마트24','세븐일레븐','미니스톱']]

In [9]:
gs_con[gs_con.상호명.isin(con_name)].head(5)

,상호명,지점명,지번주소,도로명주소,경도,위도
6,GS25등촌스타점,등촌스타점,서울특별시 강서구 등촌동 512-7,서울특별시 강서구 등촌로39길 6,126.862002,37.545577
9,CU방화진흥점,방화진흥점,서울특별시 강서구 방화동 585-4,서울특별시 강서구 초원로 30,126.808431,37.567575
20,세븐일레븐화곡곰달래지점,화곡곰달래지점,서울특별시 강서구 화곡동 918-21,서울특별시 강서구 곰달래로 104,126.844313,37.530295
22,세븐일레븐강서등촌점,강서등촌점,서울특별시 강서구 등촌동 696-1,서울특별시 강서구 공항대로41길 43,126.845520,37.559897
25,세븐일레븐등촌역점,등촌역점,서울특별시 강서구 등촌동 507-1,서울특별시 강서구 등촌로 229-1,126.863458,37.550277

1. 상호명에 지점명이 포함된 경우 - 상호명만 남기기

In [10]:
replace_df = gs_con[gs_con.상호명.isin(con_name)] # 수정이 필요한 데이터
def replace_name():
  replace_name_list = []
  for i in replace_df.상호명:
    if 'CU' in i:
      replace_name_list.append('CU')
    elif 'GS25' in i:
      replace_name_list.append('GS25')
    elif '지에스25' in i:
      replace_name_list.append('GS25')
    elif '세븐일레븐' in i:
      replace_name_list.append('세븐일레븐')
    elif '이마트24' in i :
      replace_name_list.append('이마트24')
    elif '미니스톱' in i :
      replace_name_list.append('미니스톱')
    else:
      replace_name_list.append(i)
  return replace_name_list
replace_name_list=  replace_name()

In [11]:
np.unique(replace_name_list)

array(['CU', 'GS25', '미니스톱', '세븐일레븐', '이마트24'], dtype='<U5')

In [12]:
gs_con.loc[replace_df.index,'상호명'] = replace_name_list
gs_con.head(6)

,상호명,지점명,지번주소,도로명주소,경도,위도
0,CU,강서태양점,서울특별시 강서구 화곡동 161-2,서울특별시 강서구 강서로18길 146,126.853607,37.535125
1,세븐일레븐,화곡수명점,서울특별시 강서구 화곡동 1068,서울특별시 강서구 강서로33길 103,126.834220,37.540522
2,세븐일레븐,강서내발산길점,서울특별시 강서구 내발산동 716-24,서울특별시 강서구 강서로45라길 35,126.834082,37.549387
3,CU,수명파크점,서울특별시 강서구 내발산동 751,서울특별시 강서구 수명로1길 110,126.824639,37.551852
4,CU,마곡아르디에점,서울특별시 강서구 마곡동 784-13,서울특별시 강서구 강서로 423,126.839341,37.563495
6,GS25,등촌스타점,서울특별시 강서구 등촌동 512-7,서울특별시 강서구 등촌로39길 6,126.862002,37.545577

In [13]:
gs_con.상호명.unique()

array(['CU', '세븐일레븐', 'GS25', '미니스톱', '이마트24'], dtype=object)

In [14]:
gs_con[gs_con.지점명.isnull()] # 18개 -> 직접 채우기

,상호명,지점명,지번주소,도로명주소,경도,위도
17,CU,NaN,서울특별시 강서구 방화동 608-140,서울특별시 강서구 초원로16길 24,126.815049,37.566452
26,CU,NaN,서울특별시 강서구 등촌동 65-20,서울특별시 강서구 양천로 460,126.851681,37.562570
41,GS25,NaN,서울특별시 강서구 화곡동 1032-14,서울특별시 강서구 강서로35길 8,126.838403,37.542969
66,세븐일레븐,NaN,서울특별시 강서구 가양동 1488,서울특별시 강서구 허준로 198,126.860246,37.561302
82,GS25,NaN,서울특별시 강서구 화곡동 928-35,서울특별시 강서구 곰달래로16길 29,126.840366,37.528752
89,GS25,NaN,서울특별시 강서구 내발산동 742,서울특별시 강서구 강서로47길 108,126.830521,37.553514
100,세븐일레븐,NaN,서울특별시 강서구 화곡동 662-5,서울특별시 강서구 강서로 54,126.846596,37.531948
101,GS25,NaN,서울특별시 강서구 마곡동 750,서울특별시 강서구 마곡중앙로 33,126.824067,37.558036
146,세븐일레븐,NaN,서울특별시 강서구 화곡동 1073-10,서울특별시 강서구 화곡로 142,126.837569,37.540555
176,GS25,NaN,서울특별시 강서구 염창동 272-21,서울특별시 강서구 공항대로65길 51,126.869920,37.550312
184,GS25,NaN,서울특별시 강서구 화곡동 46-235,서울특별시 강서구 까치산로 72,126.847152,37.545019
196,GS25,NaN,서울특별시 강서구 방화동 874,서울특별시 강서구 양천로6길 57,126.808015,37.569553
199,GS25,NaN,서울특별시 강서구 등촌동 654-58,서울특별시 강서구 공항대로51길 17,126.857397,37.555183
226,이마트24,NaN,서울특별시 강서구 마곡동 812,서울특별시 강서구 마곡중앙로 136,126.832900,37.572234
231,GS25,NaN,서울특별시 강서구 마곡동 741,서울특별시 강서구 마곡서1로 81,126.819134,37.564357
312,이마트24,NaN,서울특별시 강서구 마곡동 795-6,서울특별시 강서구 마곡중앙6로 89,126.837276,37.560158
324,GS25,NaN,서울특별시 강서구 방화동 830-3,서울특별시 강서구 방화대로47가길 7,126.812987,37.576523
382,GS25,NaN,서울특별시 강서구 화곡동 1021,서울특별시 강서구 화곡로21길 87,126.835898,37.544683

In [15]:
temp_name = ['방화또오기점','화곡풀향기점','가양프라자점','화곡달빛점','발산1단지점','뉴마곡14단지점','염창세빛점',
 '등촌캐빈점','마곡골든점','방화샤르망점','화곡대원점']
# 해당 위치에 편의점 없는 경우 : 26,100,146,184,196,226,231
not_con_idx = [26,100,146,184,196,226,231]

In [16]:
gs_con[gs_con.지점명.isnull()].index

Int64Index([ 17,  26,  41,  66,  82,  89, 100, 101, 146, 176, 184, 196, 199,
            226, 231, 312, 324, 382],
           dtype='int64')

In [17]:
temp_idx = gs_con[gs_con.지점명.isnull()].index
temp_idx= temp_idx.drop(not_con_idx)
temp_idx

Int64Index([17, 41, 66, 82, 89, 101, 176, 199, 312, 324, 382], dtype='int64')

In [18]:
gs_con = gs_con.drop(not_con_idx)
gs_con.loc[temp_idx,'지점명'] = temp_name

In [19]:
# 중복 데이터 확인 및 제거
gs_con[gs_con.duplicated(['상호명','지점명'], keep = False)] # 확인

,상호명,지점명,지번주소,도로명주소,경도,위도
24,GS25,마곡시티점,서울특별시 강서구 마곡동 758,서울특별시 강서구 마곡서로 170,126.825452,37.569295
29,GS25,화곡대원점,서울특별시 강서구 화곡동 1021,서울특별시 강서구 화곡로21길 87,126.835898,37.544683
65,GS25,마곡시티점,서울특별시 강서구 마곡동 758-3,서울특별시 강서구 마곡중앙5로1길 25,126.826121,37.569230
89,GS25,발산1단지점,서울특별시 강서구 내발산동 742,서울특별시 강서구 강서로47길 108,126.830521,37.553514
199,GS25,등촌캐빈점,서울특별시 강서구 등촌동 654-58,서울특별시 강서구 공항대로51길 17,126.857397,37.555183
208,GS25,등촌캐빈점,서울특별시 강서구 등촌동 654-58,서울특별시 강서구 공항대로51길 17,126.857397,37.555183
286,GS25,김포공항역점,서울특별시 강서구 마곡동 736,서울특별시 강서구 마곡서1로 132,126.819960,37.568691
317,세븐일레븐,마곡마커스점,서울특별시 강서구 마곡동 774-12,서울특별시 강서구 마곡동로 55,126.833147,37.560010
342,세븐일레븐,마곡마커스점,서울특별시 강서구 마곡동 774-9,서울특별시 강서구 마곡중앙6로 42,126.831855,37.560141
364,GS25,발산1단지점,서울특별시 강서구 내발산동 742,서울특별시 강서구 강서로47길 108,126.830521,37.553514
382,GS25,화곡대원점,서울특별시 강서구 화곡동 1021,서울특별시 강서구 화곡로21길 87,126.835898,37.544683
387,GS25,김포공항역점,서울특별시 강서구 방화동 886,서울특별시 강서구 하늘길 38,126.802364,37.561909

In [20]:
# 중복 1개씩 제거, 세븐일레븐 마곡마커스점 실제 존재 X 2개 모두 제거
drop_idx = [24,29,89,199,286,317,342]
gs_con = gs_con.drop(drop_idx)
gs_con.reset_index(drop=True,inplace = True)

In [22]:
len(gs_con) # 333개 편의점 데이터 생성

333

In [24]:
gs_con.to_csv('강서구편의점_목록.csv', encoding="utf-8-sig")