In [1]:
import pandas as pd
import numpy as np

In [2]:
con_2 = pd.read_csv('강서구편의점_목록.csv', index_col=0)
con_2.head()

,상호명,지점명,지번주소,도로명주소,경도,위도,단차/계단,확인불가
0,CU,강서태양점,서울특별시 강서구 화곡동 161-2,서울특별시 강서구 강서로18길 146,126.853607,37.535125,1,0
1,세븐일레븐,화곡수명점,서울특별시 강서구 화곡동 1068,서울특별시 강서구 강서로33길 103,126.834220,37.540522,1,0
2,세븐일레븐,강서내발산길점,서울특별시 강서구 내발산동 716-24,서울특별시 강서구 강서로45라길 35,126.834082,37.549387,0,0
3,CU,수명파크점,서울특별시 강서구 내발산동 751,서울특별시 강서구 수명로1길 110,126.824639,37.551852,0,1
4,CU,마곡아르디에점,서울특별시 강서구 마곡동 784-13,서울특별시 강서구 강서로 423,126.839341,37.563495,0,1

In [3]:
con_2 = con_2[(con_2['확인불가'] == 0) | (con_2['확인불가'] == 3)]
con_2

,상호명,지점명,지번주소,도로명주소,경도,위도,단차/계단,확인불가
0,CU,강서태양점,서울특별시 강서구 화곡동 161-2,서울특별시 강서구 강서로18길 146,126.853607,37.535125,1,0
1,세븐일레븐,화곡수명점,서울특별시 강서구 화곡동 1068,서울특별시 강서구 강서로33길 103,126.834220,37.540522,1,0
2,세븐일레븐,강서내발산길점,서울특별시 강서구 내발산동 716-24,서울특별시 강서구 강서로45라길 35,126.834082,37.549387,0,0
6,CU,우장산역점,서울특별시 강서구 내발산동 723-9,서울특별시 강서구 강서로 251,126.836003,37.548117,1,0
8,세븐일레븐,화곡우장산숲점,서울특별시 강서구 화곡동 1059-28,서울특별시 강서구 화곡로31길 22,126.842174,37.544258,1,0
...,...,...,...,...,...,...,...,...
325,CU,마곡8단지점,서울특별시 강서구 마곡동 741,서울특별시 강서구 마곡서1로 81,126.819134,37.564357,0,0
326,세븐일레븐,화곡우장산점,서울특별시 강서구 화곡동 993-36,서울특별시 강서구 화곡로53길 58,126.845766,37.552024,0,0
327,세븐일레븐,등촌임광점,서울특별시 강서구 등촌동 562-5,서울특별시 강서구 등촌로 113,126.863449,37.540437,0,0
329,GS25,뉴마곡12단지점,서울특별시 강서구 마곡동 798-12,서울특별시 강서구 마곡중앙1로 26,126.823842,37.558620,1,0
330,CU,화곡더숨점,서울특별시 강서구 화곡동 102-348,서울특별시 강서구 초록마을로34길 57,126.845050,37.538232,1,0

In [4]:
con_2 = con_2[con_2['단차/계단'] == 1]
con_2.head()

,상호명,지점명,지번주소,도로명주소,경도,위도,단차/계단,확인불가
0,CU,강서태양점,서울특별시 강서구 화곡동 161-2,서울특별시 강서구 강서로18길 146,126.853607,37.535125,1,0
1,세븐일레븐,화곡수명점,서울특별시 강서구 화곡동 1068,서울특별시 강서구 강서로33길 103,126.834220,37.540522,1,0
6,CU,우장산역점,서울특별시 강서구 내발산동 723-9,서울특별시 강서구 강서로 251,126.836003,37.548117,1,0
8,세븐일레븐,화곡우장산숲점,서울특별시 강서구 화곡동 1059-28,서울특별시 강서구 화곡로31길 22,126.842174,37.544258,1,0
9,GS25,염창사랑점,서울특별시 강서구 염창동 293,서울특별시 강서구 양천로73길 80,126.874139,37.554245,1,0

In [5]:
len(con_2)

132

In [6]:
con_2.to_csv('최종_편의점_목록.csv', index=False, encoding="utf-8-sig")